### ISSUE TITLE
Cannot use await on useQuery

### ISSUE THREAD

**Issue by snaplesec** [wheatjs/vite-plugin-vue-gql#2]
I found that I could use await with urql useQuery like this:
const { data, error } = await useQuery({query: IPquery, variables: {uname: username}})

But when using vql with this syntax:
const { error, data } = await useQuery({ uname });

Throws a fetch error and no contents returned.
Verified that removing the await on vql useQuery  it does work.

**Comment by wheatjs** [comment]
Fixed in v0.0.8, thanks!

**Comment by toddheslin** [comment]
@wheatjs I seem to be having this same problem now.

This works:
```
// in <script setup>
const { data } = useQuery('programs')
```

This doesn't:
```
// in <script setup>
const { data } = await useQuery('programs')
```

The `gql` block is:
```
<gql name="programs">
query {
  award_programs {
    id
    name
  }
}
</gql>
```

I can see the query being made in the network tab but the component is completely blank. No errors.

vue@3.1.4
vite@2.3.8
vite-plugin-vue-gql@0.2.8
graphql@15.5.1
@urql/vue@0.4.0

**Comment by wheatjs** [comment]
How are you using that component? You may need to wrap your component in a suspense component when using it. Try something like this

```html
<suspense>
  <template #default>
    <my-component></my-component>
  </template>
  <template #fallback>
    Loading Programs...
  </template>
</suspense>
```

**Comment by toddheslin** [comment]
Looks like it's generally a problem with using top level await for me. In a test component here:

This loads 'Hello world'
```vue
<template>
  <suspense>
    <template #default>
      Hello world
    </template>
    <template #fallback>
      Loading Programs...
    </template>
  </suspense>
</template>

<script setup lang="ts">

</script>
```

But this doesn't load anything at all:
```vue
<template>
  <suspense>
    <template #default>
      Hello world
    </template>
    <template #fallback>
      Loading Programs...
    </template>
  </suspense>
</template>

<script setup lang="ts">
await Promise.resolve(true)
</script>
```

For completeness, this also doesn't load anything:
```vue
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  async setup() {
    await Promise.resolve(true)
  },
})
</script>
```

OK, but I realise if I wrap the outer component in `<suspense>` it works. E.g. if the above component is called `Test.vue` and the parent wraps it like this:
```vue
<suspense>
  <Test />
</suspense>
```
This works! As also does:
```vue
<suspense>
    <template #default>
        <Test />
      </template>
      <template #fallback>
        Loading Programs...
    </template>
</suspense>
```

Sorry, I realise this is now off-topic for this library so you can close this out. But is this your understanding of how suspense is supposed to work? I thought that you could wrap suspense around a _template section_ of a component that is waiting on async data. I didn't think that this section would need to be refactored into it's _own_ component to make it work.

**Comment by wheatjs** [comment]
Sorry, I'm not too familiar with the suspense/async stuff in vue myself. Based on the [documentation](https://v3.vuejs.org/guide/migration/suspense.html#introduction) it looks like it only works by wrapping a component. Might be best to ask for more information on the suspense/async api in the vue community https://v3.vuejs.org/community/join.html

**Comment by toddheslin** [comment]
@wheatjs I've done some further testing and had some odd behavior. I think I got to the bottom of it.

My previous initialization looked like this:
```ts
createApp(App)
  .use(head)
  .use(router)
  .use(urql, {
    url: 'http://localhost:8081/v1/graphql',
    suspense: true,
    fetchOptions: {
      headers: { 'x-hasura-admin-secret': 'secret' },
    },
  })
  .mount('#app')
```

But when I added the `requestPolicy` it all worked fine:
```ts
createApp(App)
  .use(head)
  .use(router)
  .use(urql, {
    url: 'http://localhost:8081/v1/graphql',
    suspense: true,
    requestPolicy: 'cache-and-network',
    fetchOptions: {
      headers: { 'x-hasura-admin-secret': 'secret' },
    },
  })
  .mount('#app')
```

You might want to do a bit of testing around this to see if you can replicate some of the odd behavior I was seeing.

Hope this helps yourself and anyone else who comes across it 😄

**Comment by wheatjs** [comment]
Good to know, I imagine with the request policy set to `cache-and-network` it can sometimes end up pulling directly from the cache and in a sense make it as though it weren't actually an async component. Turns out the official documentation for urql has some info on vue suspense that might help you https://formidable.com/open-source/urql/docs/basics/vue/#vue-suspense
